[tool.poetry]
name = "mazegen"
version = "1.0.0"
description = "Reusable maze generator with multiple algorithms"
authors = ["rfuji-va", "haryandr"]
readme = "README.md"
packages = [{include = "mazegen"}]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0"
mypy = "^1.10"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true